[package]
name = "dtmf"
version = "0.1.0"
authors = ["Christopher Gundler <c.gundler@mail.de>"]

[[bin]]
name = "main"
doc = false

[dependencies]
clap = "2.20"
sample = "0.6"
hound = "3.0"
goertzel-filter = "0.2.0"